name: create-image

on:
  push:
    tags:
      - 'image-test-**'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: macOS-runner
    strategy:
      matrix:
        image-name: [ cicd-test ]
        app-name: [ cicd-test ]
        java-version: [17]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: ${{ matrix.java-version }}

      - name: Get tags
        run: echo ::set-output name=TAG::$(echo ${GITHUB_REF/refs\/tags\//})
        shell: bash
        id: get_tag

#      - name: Setup Paketo Cli
#        uses: buildpacks/github-actions/setup-pack@v5.0.0
#        with:
#          pack-version: '0.37.0'

      - name: gradle build # 애플리케이션 빌드를 수행합니다.
        run: ./gradlew clean build
        shell: bash

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: docker build with pack cli
        run: |
          pack build ${{ matrix.image-name }} \
            --path ./build \
            --env BP_JVM_VERSION=17 \
            --builder paketobuildpacks/builder-jammy-java-tiny \
            --cache-image ${{ vars.DOCKERHUB_USERNAME }}/${{ matrix.image-name }}:latest \
            --publish

      - name: docker tag
        run: docker tag ${{ matrix.image-name }} ${{ vars.DOCKERHUB_USERNAME }}/${{ matrix.image-name }}:latest

      - name: docker push
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/${{ matrix.image-name }}:latest
